services:
  thespeechcomingsoon:
    container_name: thespeechcomingsoon
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - npm
networks:
  npm:
    external: true
    name: npm
