services:
  thespeechcomingsoon:
    container_name: thespeechcomingsoon
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    networks:
      - npm
networks:
  npm:
    external: true
    name: npm
